# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@export
ipw_estimation <- function(m, Y, order, trace = FALSE) {
    .Call('gee4_ipw_estimation', PACKAGE = 'gee4', m, Y, order, trace)
}

#'@export
gees_estimation <- function(m, Y, X, Z, W, H, method, corrStruct, rho, start, trace = FALSE, profile = TRUE, errorMsg = FALSE) {
    .Call('gee4_gees_estimation', PACKAGE = 'gee4', m, Y, X, Z, W, H, method, corrStruct, rho, start, trace, profile, errorMsg)
}

geerfit_id <- function(m, Y, X, Z, W, rho, start, trace = FALSE, profile = TRUE, errorMsg = FALSE) {
    .Call('gee4_geerfit_id', PACKAGE = 'gee4', m, Y, X, Z, W, rho, start, trace, profile, errorMsg)
}

geerfit_cs <- function(m, Y, X, Z, W, rho, start, trace = FALSE, profile = TRUE, errorMsg = FALSE) {
    .Call('gee4_geerfit_cs', PACKAGE = 'gee4', m, Y, X, Z, W, rho, start, trace, profile, errorMsg)
}

geerfit_ar1 <- function(m, Y, X, Z, W, rho, start, trace = FALSE, profile = TRUE, errorMsg = FALSE) {
    .Call('gee4_geerfit_ar1', PACKAGE = 'gee4', m, Y, X, Z, W, rho, start, trace, profile, errorMsg)
}

